from dataclasses import dataclass
from typing import Literal, Protocol

@dataclass(frozen=True)
class NavResult:
    outcome: Literal["arrived", "navigation_failed", "cancelled"]
    reason: str | None = None

class RobotAdapter(Protocol):
    name: str
    def start_goto(self, location: dict) -> None: ...
    def poll(self, now_ms: int) -> NavResult | None: ...
    def cancel(self) -> None: ...
    def resume(self) -> None: ...
    def safety_stop(self) -> None: ...
    def state(self) -> dict: ...
